version: "3.8"
services:
  dauntless-leaderboards-mysql:
    image: mysql
    env_file:
      - ./backend/.env
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dauntless-leaderboards
      MYSQL_TCP_PORT: 7002
    ports:
      - "7002:7002"
    volumes:
      - ./database/mysql:/var/lib/mysql

  # ONLY FOR DEV PURPOSE
  dauntless-leaderboards-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: dauntless-leaderboards-mysql
      PMA_PORT: 7002
      UPLOAD_LIMIT: 500M
    ports:
      - "7003:80"

  # ONLY FOR DEPLOY PURPOSE
  # dauntless-leaderboards-server:
  #   image: node:20
  #   ports:
  #       - 7001:7001
  #   volumes:
  #       - "./backend:/app"
  #   depends_on:
  #       - dauntless-leaderboards-mysql
  #   command: >
  #       bash -c "cd /app
  #       && npm i
  #       && npm run start"