version: "3.8"
services:
  dauntless-leaderboards-mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dauntless-leaderboards
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: dauntless-leaderboards
      MYSQL_TCP_PORT: 7002
    ports:
      - "7002:7002"
    volumes:
      - ./database/mysql:/var/lib/mysql
    networks:
        - dauntless-leaderboards

  dauntless-leaderboards-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: dauntless-leaderboards-mysql
      PMA_PORT: 7002
    ports:
      - "7003:80"
    networks:
        - dauntless-leaderboards

  dauntless-leaderboards-server:
    image: node:20
    ports:
        - 7001:7001
    volumes:
        - "./backend:/app"
    depends_on:
        - dauntless-leaderboards-mysql
    command: >
        bash -c "cd /app
        && npm i
        && npm run start"
    networks:
        - dauntless-leaderboards

networks:
  dauntless-leaderboards: