version: "3.8"
services:
  dauntless-leaderboards-mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dauntless-leaderboards
      MYSQL_TCP_PORT: 7002
    ports:
      - "7002:7002"
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always

  dauntless-leaderboards-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: dauntless-leaderboards-mysql
      PMA_PORT: 7002
      PMA_USER: root
      PMA_PASSWORD: password
    ports:
      - "7003:80"