CREATE TABLE `gauntlet_seasons` (`season` INT NOT NULL , `start_at` DATETIME NOT NULL , `end_at` DATETIME NOT NULL , `flourish_id` VARCHAR(100) NULL , PRIMARY KEY (`season`)) ENGINE = InnoDB;
CREATE TABLE `guilds` (`id` INT NOT NULL AUTO_INCREMENT , `name` VARCHAR(100) NOT NULL , `tag` VARCHAR(100) NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;
INSERT INTO `guilds` (`id`, `name`, `tag`) VALUES (NULL, 'ThraxEnjoyers', 'THRAAX'), (NULL, 'DFrance', 'DFR1');
CREATE TABLE `gauntlet_leaderboard_items` (`id` INT NOT NULL AUTO_INCREMENT , `last_updated` DATETIME NOT NULL , `gauntlet_season` INT NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;
ALTER TABLE `gauntlet_leaderboard_items` ADD FOREIGN KEY (`gauntlet_season`) REFERENCES `gauntlet_seasons`(`season`) ON DELETE RESTRICT ON UPDATE RESTRICT;
CREATE TABLE `gauntlet_leaderboard_items_guilds` (`gauntlet_leaderboard_item_id` INT NOT NULL , `guild_id` INT NOT NULL , `level` INT NOT NULL , `remaining_sec` INT NOT NULL , `rank` INT NOT NULL ) ENGINE = InnoDB;
ALTER TABLE `gauntlet_leaderboard_items_guilds` ADD FOREIGN KEY (`gauntlet_leaderboard_item_id`) REFERENCES `gauntlet_leaderboard_items`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE `gauntlet_leaderboard_items_guilds` ADD FOREIGN KEY (`guild_id`) REFERENCES `guilds`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;
CREATE TABLE `guilds_data` (`guild_id` INT NOT NULL , `icon_filename` VARCHAR(100) NOT NULL , `discord_link` VARCHAR(100) NOT NULL , `detail_html` LONGTEXT NOT NULL , PRIMARY KEY (`guild_id`)) ENGINE = InnoDB;
ALTER TABLE `guilds_data` ADD FOREIGN KEY (`guild_id`) REFERENCES `guilds`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;
CREATE TABLE `players` (`id` INT NOT NULL AUTO_INCREMENT , `phx_id` VARCHAR(100) NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;
INSERT INTO `players` (`id`, `phx_id`) VALUES (NULL, 'ZSOHUWKWT5CDHB5SPLSLFCBJYQ'), (NULL, 'H2HYMA2DTVFJFGKMAFIDN3AMLQ');
CREATE TABLE `platforms` (`id` INT NOT NULL AUTO_INCREMENT , `name` VARCHAR(3) NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;
INSERT INTO `platforms` (`id`, `name`) VALUES (NULL, 'WIN'), (NULL, 'PSN'), (NULL, 'XBL'), (NULL, 'SWT');
CREATE TABLE `player_names` (`player_id` INT NOT NULL , `platform_id` INT NOT NULL , `name` VARCHAR(100) NOT NULL ) ENGINE = InnoDB;
ALTER TABLE `player_names` ADD UNIQUE(`player_id`, `platform_id`);
CREATE TABLE `players_data` (`player_id` INT NOT NULL , `icon_filename` VARCHAR(100) NOT NULL , PRIMARY KEY (`player_id`)) ENGINE = InnoDB;
ALTER TABLE `players_data` ADD FOREIGN KEY (`player_id`) REFERENCES `players`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;
CREATE TABLE `trial_weeks` (`week` INT NOT NULL , `start_at` DATETIME NOT NULL , `end_at` DATETIME NOT NULL , `behemoth_id` INT NOT NULL , PRIMARY KEY (`week`)) ENGINE = InnoDB;
CREATE TABLE `behemoths` (`id` INT NOT NULL AUTO_INCREMENT , `name` VARCHAR(30) NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;
ALTER TABLE `trial_weeks` ADD FOREIGN KEY (`behemoth_id`) REFERENCES `behemoths`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;
CREATE TABLE `trial_leaderboard_items` (`id` INT NOT NULL AUTO_INCREMENT , `trial_week` INT NOT NULL , `last_updated` DATETIME NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;
ALTER TABLE `trial_leaderboard_items` ADD FOREIGN KEY (`trial_week`) REFERENCES `trial_weeks`(`week`) ON DELETE RESTRICT ON UPDATE RESTRICT;
CREATE TABLE `trial_leaderboard_item_type` (`id` INT NOT NULL AUTO_INCREMENT , `type` VARCHAR(20) NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;
INSERT INTO `trial_leaderboard_item_type` (`id`, `type`) VALUES (NULL, 'all'), (NULL, 'group'), (NULL, 'sword'), (NULL, 'axe'), (NULL, 'hammer'), (NULL, 'chainblades'), (NULL, 'pike'), (NULL, 'repeaters'), (NULL, 'strikers');
CREATE TABLE `trial_leaderboard_items_groups` (`id` INT NOT NULL AUTO_INCREMENT , `trial_leaderboard_item_id` INT NOT NULL , `trial_leaderboard_item_type_id` INT NOT NULL , `objectives_completed` INT NOT NULL , `completion_time` INT NOT NULL , `rank` INT NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;
ALTER TABLE `trial_leaderboard_items_groups` ADD FOREIGN KEY (`trial_leaderboard_item_id`) REFERENCES `trial_leaderboard_items`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `trial_leaderboard_items_groups` ADD FOREIGN KEY (`trial_leaderboard_item_type_id`) REFERENCES `trial_leaderboard_item_type`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE `trial_leaderboard_items_groups` ADD UNIQUE(`trial_leaderboard_item_id`, `trial_leaderboard_item_type_id`, `rank`);
CREATE TABLE `trial_leaderboard_items_groups_players` (`trial_leaderboard_items_trial_groups_id` int NOT NULL , `player_id` int NOT NULL , `platform_id` int NOT NULL , `weapon_id` int NOT NULL , `role_id` varchar(30) NOT NULL) ENGINE = InnoDB;
ALTER TABLE `trial_leaderboard_items_groups_players` ADD FOREIGN KEY (`trial_leaderboard_items_trial_groups_id`) REFERENCES `trial_leaderboard_items_groups`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `trial_leaderboard_items_groups_players` ADD FOREIGN KEY (`player_id`) REFERENCES `players`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE `trial_leaderboard_items_groups_players` ADD FOREIGN KEY (`platform_id`) REFERENCES `platforms`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE `trial_leaderboard_items_groups_players` ADD UNIQUE(`trial_leaderboard_items_trial_groups_id`, `player_id`);