export function getSeasonNumberFromSeasonId(id: string): number {
    return Number(id.slice(15));
}

export function getTimestampFromDate(date: Date): number {
    return Math.floor(new Date(date).getTime() / 1000);
}

export function getCurrentWeek(): number {
    const week1StartDate = new Date(Date.UTC(2019, 7 - 1, 18, 18));
    const weekInMs = 1 * 7 * 24 * 60 * 60 * 1000;
    return Math.floor((new Date().getTime() - week1StartDate.getTime()) / weekInMs) + 1
}

export function getWeekStartDate(week: number): Date {
    const week1StartDate = new Date(Date.UTC(2019, 7 - 1, 18, 18));
    const weekInMs = 1 * 7 * 24 * 60 * 60 * 1000;
    return new Date(week1StartDate.getTime() + weekInMs * (week - 1));
}

export function getWeekEndDate(week: number): Date {
    const week1StartDate = new Date(Date.UTC(2019, 7 - 1, 18, 18));
    const weekInMs = 1 * 7 * 24 * 60 * 60 * 1000;
    return new Date(week1StartDate.getTime() + weekInMs * week);
}

enum BEHEMOTH {
    'Moonreaver_Shrike',
    'Thunderdeep_Drask',
    'Flameborn_Quillshot',
    'Shadowtouched_Koshai',
    'Rockfall_Skarn',
    'Koshai',
    'Shrowd',
    'Ragetail_Gnasher',
    'Winterhorn_Skraev',
    'Firebrand_Charrogg',
    'Phaelanx',
    'Tempestborne_Stormclaw',
    'Malkarion',
    'Rezakiri',
    'Riftstalker',
    'Drask',
    'Bloodfire_Embermane',
    'Shadowtouched_Nayzaga',
    'Deadeye_Quillshot',
    'Frostback_Pangar',
    'Razorwing_Kharabak',
    'Shadowtouched_Drask',
    'Shockjaw_Nayzaga',
    'Dreadfrost_Boreus',
    'Bloodshot_Shrowd',
}

const behemothNames = [
    'Moonreaver Shrike',
    'Thunderdeep Drask',
    'Flameborn Quillshot',
    'Shadowtouched Koshai',
    'Rockfall Skarn',
    'Koshai',
    'Shrowd',
    'Ragetail Gnasher',
    'Winterhorn Skraev',
    'Firebrand Charrogg',
    'Phaelanx',
    'Tempestborne Stormclaw',
    'Malkarion',
    'Rezakiri',
    'Riftstalker',
    'Drask',
    'Bloodfire Embermane',
    'Shadowtouched Nayzaga',
    'Deadeye Quillshot',
    'Frostback Pangar',
    'Razorwing Kharabak',
    'Shadowtouched Drask',
    'Shockjaw Nayzaga',
    'Dreadfrost Boreus',
    'Bloodshot Shrowd',
];

const behemothRotationHistory = [
    BEHEMOTH.Shockjaw_Nayzaga,
    BEHEMOTH.Shrowd,
    BEHEMOTH.Deadeye_Quillshot,
    BEHEMOTH.Bloodfire_Embermane,
    BEHEMOTH.Winterhorn_Skraev,
    BEHEMOTH.Razorwing_Kharabak,
    BEHEMOTH.Koshai,
    BEHEMOTH.Rezakiri,
    BEHEMOTH.Firebrand_Charrogg,
    BEHEMOTH.Moonreaver_Shrike,
    BEHEMOTH.Rockfall_Skarn,
    BEHEMOTH.Frostback_Pangar,
    BEHEMOTH.Ragetail_Gnasher,
    BEHEMOTH.Shockjaw_Nayzaga,
    BEHEMOTH.Shrowd,
    BEHEMOTH.Deadeye_Quillshot,
    BEHEMOTH.Bloodfire_Embermane,
    BEHEMOTH.Winterhorn_Skraev,
    BEHEMOTH.Razorwing_Kharabak,
    BEHEMOTH.Koshai,
    BEHEMOTH.Rezakiri,
    BEHEMOTH.Firebrand_Charrogg,
    BEHEMOTH.Moonreaver_Shrike,
    BEHEMOTH.Rockfall_Skarn,
    BEHEMOTH.Frostback_Pangar,
    BEHEMOTH.Ragetail_Gnasher,
    BEHEMOTH.Shockjaw_Nayzaga,
    BEHEMOTH.Shrowd,
    BEHEMOTH.Deadeye_Quillshot,
    BEHEMOTH.Bloodfire_Embermane,
    BEHEMOTH.Winterhorn_Skraev,
    BEHEMOTH.Razorwing_Kharabak,
    BEHEMOTH.Koshai,
    BEHEMOTH.Rezakiri,
    BEHEMOTH.Firebrand_Charrogg,
    BEHEMOTH.Moonreaver_Shrike,
    BEHEMOTH.Rockfall_Skarn,
    BEHEMOTH.Frostback_Pangar,
    BEHEMOTH.Ragetail_Gnasher,
    BEHEMOTH.Shockjaw_Nayzaga,
    BEHEMOTH.Shrowd,
    BEHEMOTH.Deadeye_Quillshot,
    BEHEMOTH.Malkarion,
    BEHEMOTH.Tempestborne_Stormclaw,
    BEHEMOTH.Dreadfrost_Boreus,
    BEHEMOTH.Drask,
    BEHEMOTH.Bloodfire_Embermane,
    BEHEMOTH.Winterhorn_Skraev,
    BEHEMOTH.Malkarion,
    BEHEMOTH.Razorwing_Kharabak,
    BEHEMOTH.Koshai,
    BEHEMOTH.Tempestborne_Stormclaw,
    BEHEMOTH.Rezakiri,
    BEHEMOTH.Firebrand_Charrogg,
    BEHEMOTH.Dreadfrost_Boreus,
    BEHEMOTH.Moonreaver_Shrike,
    BEHEMOTH.Rockfall_Skarn,
    BEHEMOTH.Shadowtouched_Koshai,
    BEHEMOTH.Drask,
    BEHEMOTH.Ragetail_Gnasher,
    BEHEMOTH.Shadowtouched_Nayzaga,
    BEHEMOTH.Deadeye_Quillshot,
    BEHEMOTH.Shadowtouched_Drask,
    BEHEMOTH.Bloodfire_Embermane,
    BEHEMOTH.Winterhorn_Skraev,
    BEHEMOTH.Malkarion,
    BEHEMOTH.Razorwing_Kharabak,
    BEHEMOTH.Koshai,
    BEHEMOTH.Tempestborne_Stormclaw,
    BEHEMOTH.Rezakiri,
    BEHEMOTH.Dreadfrost_Boreus,
    BEHEMOTH.Firebrand_Charrogg,
    BEHEMOTH.Moonreaver_Shrike,
    BEHEMOTH.Rockfall_Skarn,
    BEHEMOTH.Frostback_Pangar,
    BEHEMOTH.Drask,
    BEHEMOTH.Ragetail_Gnasher,
    BEHEMOTH.Shadowtouched_Nayzaga,
    BEHEMOTH.Tempestborne_Stormclaw,
    BEHEMOTH.Winterhorn_Skraev,
    BEHEMOTH.Razorwing_Kharabak,
    BEHEMOTH.Shrowd,
    BEHEMOTH.Koshai,
    BEHEMOTH.Shadowtouched_Drask,
    BEHEMOTH.Malkarion,
    BEHEMOTH.Shadowtouched_Koshai,
    BEHEMOTH.Deadeye_Quillshot,
    BEHEMOTH.Bloodfire_Embermane,
    BEHEMOTH.Winterhorn_Skraev,
    BEHEMOTH.Malkarion,
    BEHEMOTH.Razorwing_Kharabak,
    BEHEMOTH.Koshai,
    BEHEMOTH.Tempestborne_Stormclaw,
    BEHEMOTH.Rezakiri,
    BEHEMOTH.Dreadfrost_Boreus,
    BEHEMOTH.Firebrand_Charrogg,
    BEHEMOTH.Moonreaver_Shrike,
    BEHEMOTH.Rockfall_Skarn,
    BEHEMOTH.Frostback_Pangar,
    BEHEMOTH.Drask,
    BEHEMOTH.Ragetail_Gnasher,
    BEHEMOTH.Shadowtouched_Nayzaga,
    BEHEMOTH.Koshai,
    BEHEMOTH.Shrowd,
    BEHEMOTH.Shadowtouched_Drask,
    BEHEMOTH.Malkarion,
    BEHEMOTH.Shadowtouched_Koshai,
    BEHEMOTH.Deadeye_Quillshot,
    BEHEMOTH.Bloodfire_Embermane,
    BEHEMOTH.Winterhorn_Skraev,
    BEHEMOTH.Razorwing_Kharabak,
    BEHEMOTH.Tempestborne_Stormclaw,
    BEHEMOTH.Rezakiri,
    BEHEMOTH.Dreadfrost_Boreus,
    BEHEMOTH.Firebrand_Charrogg,
    BEHEMOTH.Moonreaver_Shrike,
    BEHEMOTH.Rockfall_Skarn,
    BEHEMOTH.Frostback_Pangar,
    BEHEMOTH.Drask,
    BEHEMOTH.Shrowd,
    BEHEMOTH.Ragetail_Gnasher,
    BEHEMOTH.Bloodfire_Embermane,
    BEHEMOTH.Moonreaver_Shrike,
    BEHEMOTH.Shadowtouched_Nayzaga,
    BEHEMOTH.Koshai,
    BEHEMOTH.Malkarion,
    BEHEMOTH.Deadeye_Quillshot,
    BEHEMOTH.Winterhorn_Skraev,
    BEHEMOTH.Frostback_Pangar,
    BEHEMOTH.Razorwing_Kharabak,
    BEHEMOTH.Tempestborne_Stormclaw,
    BEHEMOTH.Shadowtouched_Drask,
    BEHEMOTH.Rezakiri,
    BEHEMOTH.Drask,
    BEHEMOTH.Firebrand_Charrogg,
    BEHEMOTH.Shadowtouched_Koshai,
    BEHEMOTH.Rockfall_Skarn,
    BEHEMOTH.Dreadfrost_Boreus,
    BEHEMOTH.Koshai,
    BEHEMOTH.Moonreaver_Shrike,
    BEHEMOTH.Shrowd,
    BEHEMOTH.Ragetail_Gnasher,
    BEHEMOTH.Winterhorn_Skraev,
    BEHEMOTH.Tempestborne_Stormclaw,
    BEHEMOTH.Malkarion,
    BEHEMOTH.Rezakiri,
    BEHEMOTH.Bloodfire_Embermane,
    BEHEMOTH.Shadowtouched_Nayzaga,
    BEHEMOTH.Deadeye_Quillshot,
    BEHEMOTH.Frostback_Pangar,
    BEHEMOTH.Razorwing_Kharabak,
    BEHEMOTH.Shadowtouched_Drask,
    BEHEMOTH.Moonreaver_Shrike,
    BEHEMOTH.Drask,
    BEHEMOTH.Firebrand_Charrogg,
    BEHEMOTH.Shadowtouched_Koshai,
    BEHEMOTH.Rockfall_Skarn,
    BEHEMOTH.Koshai,
    BEHEMOTH.Shrowd,
    BEHEMOTH.Ragetail_Gnasher,
    BEHEMOTH.Winterhorn_Skraev,
    BEHEMOTH.Phaelanx,
    BEHEMOTH.Tempestborne_Stormclaw,
    BEHEMOTH.Malkarion,
    BEHEMOTH.Rezakiri,
    BEHEMOTH.Bloodfire_Embermane,
    BEHEMOTH.Shadowtouched_Nayzaga,
    BEHEMOTH.Deadeye_Quillshot,
    BEHEMOTH.Frostback_Pangar,
    BEHEMOTH.Razorwing_Kharabak,
    BEHEMOTH.Shadowtouched_Drask,
    BEHEMOTH.Moonreaver_Shrike,
    BEHEMOTH.Thunderdeep_Drask,
    BEHEMOTH.Flameborn_Quillshot,
    BEHEMOTH.Shadowtouched_Koshai,
    BEHEMOTH.Rockfall_Skarn,
    BEHEMOTH.Koshai,
    BEHEMOTH.Bloodshot_Shrowd,
    BEHEMOTH.Ragetail_Gnasher,
    BEHEMOTH.Winterhorn_Skraev,
    BEHEMOTH.Firebrand_Charrogg,
    BEHEMOTH.Phaelanx,
    BEHEMOTH.Tempestborne_Stormclaw,
    BEHEMOTH.Malkarion,
    BEHEMOTH.Rezakiri,
    BEHEMOTH.Bloodfire_Embermane,
    BEHEMOTH.Shadowtouched_Nayzaga,
    BEHEMOTH.Deadeye_Quillshot,
    BEHEMOTH.Frostback_Pangar,
    BEHEMOTH.Razorwing_Kharabak,
    BEHEMOTH.Shadowtouched_Drask,
    BEHEMOTH.Moonreaver_Shrike,
    BEHEMOTH.Thunderdeep_Drask,
    BEHEMOTH.Flameborn_Quillshot,
    BEHEMOTH.Shadowtouched_Koshai,
    BEHEMOTH.Rockfall_Skarn,
    BEHEMOTH.Koshai,
    BEHEMOTH.Bloodshot_Shrowd,
    BEHEMOTH.Ragetail_Gnasher,
    BEHEMOTH.Winterhorn_Skraev,
    BEHEMOTH.Firebrand_Charrogg,
    BEHEMOTH.Phaelanx,
    BEHEMOTH.Tempestborne_Stormclaw,
    BEHEMOTH.Malkarion,
    BEHEMOTH.Rezakiri,
    BEHEMOTH.Riftstalker,
    BEHEMOTH.Drask,
    BEHEMOTH.Bloodfire_Embermane,
    BEHEMOTH.Shadowtouched_Nayzaga,
    BEHEMOTH.Deadeye_Quillshot,
    BEHEMOTH.Frostback_Pangar,
    BEHEMOTH.Razorwing_Kharabak,
    BEHEMOTH.Shadowtouched_Drask
];

const currentBehemothRotation = [
    BEHEMOTH.Moonreaver_Shrike,
    BEHEMOTH.Thunderdeep_Drask,
    BEHEMOTH.Flameborn_Quillshot,
    BEHEMOTH.Shadowtouched_Koshai,
    BEHEMOTH.Rockfall_Skarn,
    BEHEMOTH.Koshai,
    BEHEMOTH.Shrowd,
    BEHEMOTH.Ragetail_Gnasher,
    BEHEMOTH.Winterhorn_Skraev,
    BEHEMOTH.Firebrand_Charrogg,
    BEHEMOTH.Phaelanx,
    BEHEMOTH.Tempestborne_Stormclaw,
    BEHEMOTH.Malkarion,
    BEHEMOTH.Rezakiri,
    BEHEMOTH.Riftstalker,
    BEHEMOTH.Drask,
    BEHEMOTH.Bloodfire_Embermane,
    BEHEMOTH.Shadowtouched_Nayzaga,
    BEHEMOTH.Deadeye_Quillshot,
    BEHEMOTH.Frostback_Pangar,
    BEHEMOTH.Razorwing_Kharabak,
    BEHEMOTH.Shadowtouched_Drask
];

export function getBehemothNameFromWeek(week: number): string {
    if (week < behemothRotationHistory.length) return behemothNames[behemothRotationHistory[week - 1]];
    let index = (week - behemothRotationHistory.length) % currentBehemothRotation.length - 1;
    if (index === -1) { index = currentBehemothRotation.length - 1; }
    return behemothNames[currentBehemothRotation[index]];
}