export function getSeasonNumberFromSeasonId(id: string): number {
    return Number(id.slice(15));
}

export function getTimestampFromDate(date: Date): number {
    return Math.floor(new Date(date).getTime() / 1000);
}

export function getCurrentWeek(): number {
    const week1StartDate = new Date(Date.UTC(2019, 7 - 1, 18, 18));
    const weekInMs = 1 * 7 * 24 * 60 * 60 * 1000;
    return Math.floor((new Date().getTime() - week1StartDate.getTime()) / weekInMs) + 1
}

export function getWeekStartDate(week: number): Date {
    const week1StartDate = new Date(Date.UTC(2019, 7 - 1, 18, 18));
    const weekInMs = 1 * 7 * 24 * 60 * 60 * 1000;
    return new Date(week1StartDate.getTime() + weekInMs * (week - 1));
}

export function getWeekEndDate(week: number): Date {
    const week1StartDate = new Date(Date.UTC(2019, 7 - 1, 18, 18));
    const weekInMs = 1 * 7 * 24 * 60 * 60 * 1000;
    return new Date(week1StartDate.getTime() + weekInMs * week);
}

enum BEHEMOTH {
    'Shrike',
    'Thunderdeep_Drask',
    'Blaze_Quillshot',
    'Shadowtouched_Koshai',
    'Skarn',
    'Koshai',
    'Shrowd',
    'Gnasher',
    'Skraev',
    'Charrogg',
    'Phaelanx',
    'Stormclaw',
    'Malkarion',
    'Rezakiri',
    'Riftstalker',
    'Drask',
    'Embermane',
    'Shadowtouched_Nayzaga',
    'Quillshot',
    'Pangar',
    'Kharabak',
    'Shadowtouched_Drask',
    'Nayzaga',
    'Boreus',
    'Bloodshot_Shrowd',
}

const behemothNames = [
    'Shrike',
    'Thunderdeep Drask',
    'Blaze Quillshot',
    'Shadowtouched Koshai',
    'Skarn',
    'Koshai',
    'Shrowd',
    'Gnasher',
    'Skraev',
    'Charrogg',
    'Phaelanx',
    'Stormclaw',
    'Malkarion',
    'Rezakiri',
    'Riftstalker',
    'Drask',
    'Embermane',
    'Shadowtouched Nayzaga',
    'Quillshot',
    'Pangar',
    'Kharabak',
    'Shadowtouched Drask',
    'Nayzaga',
    'Boreus',
    'Bloodshot Shrowd',
];

const behemothRotationHistory = [
    BEHEMOTH.Nayzaga,
    BEHEMOTH.Shrowd,
    BEHEMOTH.Quillshot,
    BEHEMOTH.Embermane,
    BEHEMOTH.Skraev,
    BEHEMOTH.Kharabak,
    BEHEMOTH.Koshai,
    BEHEMOTH.Rezakiri,
    BEHEMOTH.Charrogg,
    BEHEMOTH.Shrike,
    BEHEMOTH.Skarn,
    BEHEMOTH.Pangar,
    BEHEMOTH.Gnasher,
    BEHEMOTH.Nayzaga,
    BEHEMOTH.Shrowd,
    BEHEMOTH.Quillshot,
    BEHEMOTH.Embermane,
    BEHEMOTH.Skraev,
    BEHEMOTH.Kharabak,
    BEHEMOTH.Koshai,
    BEHEMOTH.Rezakiri,
    BEHEMOTH.Charrogg,
    BEHEMOTH.Shrike,
    BEHEMOTH.Skarn,
    BEHEMOTH.Pangar,
    BEHEMOTH.Gnasher,
    BEHEMOTH.Nayzaga,
    BEHEMOTH.Shrowd,
    BEHEMOTH.Quillshot,
    BEHEMOTH.Embermane,
    BEHEMOTH.Skraev,
    BEHEMOTH.Kharabak,
    BEHEMOTH.Koshai,
    BEHEMOTH.Rezakiri,
    BEHEMOTH.Charrogg,
    BEHEMOTH.Shrike,
    BEHEMOTH.Skarn,
    BEHEMOTH.Pangar,
    BEHEMOTH.Gnasher,
    BEHEMOTH.Nayzaga,
    BEHEMOTH.Shrowd,
    BEHEMOTH.Quillshot,
    BEHEMOTH.Malkarion,
    BEHEMOTH.Stormclaw,
    BEHEMOTH.Boreus,
    BEHEMOTH.Drask,
    BEHEMOTH.Embermane,
    BEHEMOTH.Skraev,
    BEHEMOTH.Malkarion,
    BEHEMOTH.Kharabak,
    BEHEMOTH.Koshai,
    BEHEMOTH.Stormclaw,
    BEHEMOTH.Rezakiri,
    BEHEMOTH.Charrogg,
    BEHEMOTH.Boreus,
    BEHEMOTH.Shrike,
    BEHEMOTH.Skarn,
    BEHEMOTH.Shadowtouched_Koshai,
    BEHEMOTH.Drask,
    BEHEMOTH.Gnasher,
    BEHEMOTH.Shadowtouched_Nayzaga,
    BEHEMOTH.Quillshot,
    BEHEMOTH.Shadowtouched_Drask,
    BEHEMOTH.Embermane,
    BEHEMOTH.Skraev,
    BEHEMOTH.Malkarion,
    BEHEMOTH.Kharabak,
    BEHEMOTH.Koshai,
    BEHEMOTH.Stormclaw,
    BEHEMOTH.Rezakiri,
    BEHEMOTH.Boreus,
    BEHEMOTH.Charrogg,
    BEHEMOTH.Shrike,
    BEHEMOTH.Skarn,
    BEHEMOTH.Pangar,
    BEHEMOTH.Drask,
    BEHEMOTH.Gnasher,
    BEHEMOTH.Shadowtouched_Nayzaga,
    BEHEMOTH.Stormclaw,
    BEHEMOTH.Skraev,
    BEHEMOTH.Kharabak,
    BEHEMOTH.Shrowd,
    BEHEMOTH.Koshai,
    BEHEMOTH.Shadowtouched_Drask,
    BEHEMOTH.Malkarion,
    BEHEMOTH.Shadowtouched_Koshai,
    BEHEMOTH.Quillshot,
    BEHEMOTH.Embermane,
    BEHEMOTH.Skraev,
    BEHEMOTH.Malkarion,
    BEHEMOTH.Kharabak,
    BEHEMOTH.Koshai,
    BEHEMOTH.Stormclaw,
    BEHEMOTH.Rezakiri,
    BEHEMOTH.Boreus,
    BEHEMOTH.Charrogg,
    BEHEMOTH.Shrike,
    BEHEMOTH.Skarn,
    BEHEMOTH.Pangar,
    BEHEMOTH.Drask,
    BEHEMOTH.Gnasher,
    BEHEMOTH.Shadowtouched_Nayzaga,
    BEHEMOTH.Koshai,
    BEHEMOTH.Shrowd,
    BEHEMOTH.Shadowtouched_Drask,
    BEHEMOTH.Malkarion,
    BEHEMOTH.Shadowtouched_Koshai,
    BEHEMOTH.Quillshot,
    BEHEMOTH.Embermane,
    BEHEMOTH.Skraev,
    BEHEMOTH.Kharabak,
    BEHEMOTH.Stormclaw,
    BEHEMOTH.Rezakiri,
    BEHEMOTH.Boreus,
    BEHEMOTH.Charrogg,
    BEHEMOTH.Shrike,
    BEHEMOTH.Skarn,
    BEHEMOTH.Pangar,
    BEHEMOTH.Drask,
    BEHEMOTH.Shrowd,
    BEHEMOTH.Gnasher,
    BEHEMOTH.Embermane,
    BEHEMOTH.Shrike,
    BEHEMOTH.Shadowtouched_Nayzaga,
    BEHEMOTH.Koshai,
    BEHEMOTH.Malkarion,
    BEHEMOTH.Quillshot,
    BEHEMOTH.Skraev,
    BEHEMOTH.Pangar,
    BEHEMOTH.Kharabak,
    BEHEMOTH.Stormclaw,
    BEHEMOTH.Shadowtouched_Drask,
    BEHEMOTH.Rezakiri,
    BEHEMOTH.Drask,
    BEHEMOTH.Charrogg,
    BEHEMOTH.Shadowtouched_Koshai,
    BEHEMOTH.Skarn,
    BEHEMOTH.Boreus,
    BEHEMOTH.Koshai,
    BEHEMOTH.Shrike,
    BEHEMOTH.Shrowd,
    BEHEMOTH.Gnasher,
    BEHEMOTH.Skraev,
    BEHEMOTH.Stormclaw,
    BEHEMOTH.Malkarion,
    BEHEMOTH.Rezakiri,
    BEHEMOTH.Embermane,
    BEHEMOTH.Shadowtouched_Nayzaga,
    BEHEMOTH.Quillshot,
    BEHEMOTH.Pangar,
    BEHEMOTH.Kharabak,
    BEHEMOTH.Shadowtouched_Drask,
    BEHEMOTH.Shrike,
    BEHEMOTH.Drask,
    BEHEMOTH.Charrogg,
    BEHEMOTH.Shadowtouched_Koshai,
    BEHEMOTH.Skarn,
    BEHEMOTH.Koshai,
    BEHEMOTH.Shrowd,
    BEHEMOTH.Gnasher,
    BEHEMOTH.Skraev,
    BEHEMOTH.Phaelanx,
    BEHEMOTH.Stormclaw,
    BEHEMOTH.Malkarion,
    BEHEMOTH.Rezakiri,
    BEHEMOTH.Embermane,
    BEHEMOTH.Shadowtouched_Nayzaga,
    BEHEMOTH.Quillshot,
    BEHEMOTH.Pangar,
    BEHEMOTH.Kharabak,
    BEHEMOTH.Shadowtouched_Drask,
    BEHEMOTH.Shrike,
    BEHEMOTH.Thunderdeep_Drask,
    BEHEMOTH.Blaze_Quillshot,
    BEHEMOTH.Shadowtouched_Koshai,
    BEHEMOTH.Skarn,
    BEHEMOTH.Koshai,
    BEHEMOTH.Bloodshot_Shrowd,
    BEHEMOTH.Gnasher,
    BEHEMOTH.Skraev,
    BEHEMOTH.Charrogg,
    BEHEMOTH.Phaelanx,
    BEHEMOTH.Stormclaw,
    BEHEMOTH.Malkarion,
    BEHEMOTH.Rezakiri,
    BEHEMOTH.Embermane,
    BEHEMOTH.Shadowtouched_Nayzaga,
    BEHEMOTH.Quillshot,
    BEHEMOTH.Pangar,
    BEHEMOTH.Kharabak,
    BEHEMOTH.Shadowtouched_Drask,
    BEHEMOTH.Shrike,
    BEHEMOTH.Thunderdeep_Drask,
    BEHEMOTH.Blaze_Quillshot,
    BEHEMOTH.Shadowtouched_Koshai,
    BEHEMOTH.Skarn,
    BEHEMOTH.Koshai,
    BEHEMOTH.Bloodshot_Shrowd,
    BEHEMOTH.Gnasher,
    BEHEMOTH.Skraev,
    BEHEMOTH.Charrogg,
    BEHEMOTH.Phaelanx,
    BEHEMOTH.Stormclaw,
    BEHEMOTH.Malkarion,
    BEHEMOTH.Rezakiri,
    BEHEMOTH.Riftstalker,
    BEHEMOTH.Drask,
    BEHEMOTH.Embermane,
    BEHEMOTH.Shadowtouched_Nayzaga,
    BEHEMOTH.Quillshot,
    BEHEMOTH.Pangar,
    BEHEMOTH.Kharabak,
    BEHEMOTH.Shadowtouched_Drask
];

const currentBehemothRotation = [
    BEHEMOTH.Shrike,
    BEHEMOTH.Thunderdeep_Drask,
    BEHEMOTH.Blaze_Quillshot,
    BEHEMOTH.Shadowtouched_Koshai,
    BEHEMOTH.Skarn,
    BEHEMOTH.Koshai,
    BEHEMOTH.Shrowd,
    BEHEMOTH.Gnasher,
    BEHEMOTH.Skraev,
    BEHEMOTH.Charrogg,
    BEHEMOTH.Phaelanx,
    BEHEMOTH.Stormclaw,
    BEHEMOTH.Malkarion,
    BEHEMOTH.Rezakiri,
    BEHEMOTH.Riftstalker,
    BEHEMOTH.Drask,
    BEHEMOTH.Embermane,
    BEHEMOTH.Shadowtouched_Nayzaga,
    BEHEMOTH.Quillshot,
    BEHEMOTH.Pangar,
    BEHEMOTH.Kharabak,
    BEHEMOTH.Shadowtouched_Drask
];

export function getBehemothNameFromWeek(week: number): string {
    if (week < behemothRotationHistory.length) return behemothNames[behemothRotationHistory[week - 1]];
    let index = (week - behemothRotationHistory.length) % currentBehemothRotation.length - 1;
    if (index === -1) { index = currentBehemothRotation.length - 1; }
    return behemothNames[currentBehemothRotation[index]];
}